Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2018-12, with the labels that each got.

#270 Git ignore example openapi violation report
  .gitignore
  example/violations.report
Labels: cncf-cla: yes, size/M

#273 Feat(apiserver-boot): make local etcd's storage class configurable
  cmd/apiserver-boot/boot/build/build_resource_config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/squash

#275 change version of apiregistration.k8s.io to v1
  cmd/apiserver-boot/boot/build/build_resource_config.go
  example/config/apiserver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/squash

#267 Add informative docs for AA / CRD comparision
  docs/compare_with_kubebuilder.md
Labels: cncf-cla: yes, kind/documentation, sig/api-machinery, size/M

#282 Feat(build-docs): run local etcd by default
  cmd/apiserver-boot/boot/build/docs.go
Labels: cncf-cla: yes, size/S

#287 Bugfix(apiserver-boot): ensure "make install" dependencies for apiserver-boot
  Makefile
Labels: cncf-cla: yes, kind/bug, size/XS

#291 Chore(README): Note brief aggregated apisever use-case on home README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#292 Release: bump version to v1.12.alpha.0
  VERSION
Labels: cncf-cla: yes, size/XS

#293 Chore: Remove unexpected empty file tarred in vendor
  cmd/apiserver-builder-release/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#294 Chore: Reuse apiserver-build-release in make install
  Makefile
  cmd/apiserver-builder-release/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#295 adding Security Contact
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S
