Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2018-11, with the labels that each got.

#265 Resume maintainance and fold deprecation notes
  .gitignore
  README.md
Labels: cncf-cla: yes, size/XS

#264 Fix typos: serveral -> several
  docs/concepts/aggregation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#268 Deprecate internal client/informer/lister generation
  cmd/apiserver-boot/boot/build/build_executables.go
  cmd/apiserver-boot/boot/build/generate.go
Labels: cncf-cla: yes, kind/cleanup, sig/api-machinery, size/S
