Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-09, with the labels that each got.

#413 Chore: Compatibility for exported typo from 1.12+ generator
  pkg/builders/api_version_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#414 Chore: Completely moving to k8s.io/klog
  cmd/apiregister-gen/generators/parser.go
  cmd/apiserver-boot/boot/build/build_container.go
  cmd/apiserver-boot/boot/build/build_executables.go
  cmd/apiserver-boot/boot/build/build_resource_config.go
  cmd/apiserver-boot/boot/build/docs.go
  cmd/apiserver-boot/boot/build/generate.go
  cmd/apiserver-boot/boot/create/controller.go
  cmd/apiserver-boot/boot/create/controller_test_suite.go
  cmd/apiserver-boot/boot/create/group.go
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/create/subresource.go
  cmd/apiserver-boot/boot/create/util.go
  cmd/apiserver-boot/boot/create/version.go
  cmd/apiserver-boot/boot/init_repo/repo.go
  cmd/apiserver-boot/boot/init_repo/vendor.go
  cmd/apiserver-boot/boot/run/local.go
  cmd/apiserver-boot/boot/run/local_aggregated.go
  cmd/apiserver-boot/boot/util/util.go
  cmd/apiserver-boot/boot/version/version.go
  cmd/apiserver-boot/main.go
  cmd/apiserver-builder-release/main.go
  example/basic/cmd/controller-manager/BUILD.bazel
  example/basic/cmd/controller-manager/main.go
  example/basic/pkg/apis/kingsport/festival_strategy.go
  example/basic/pkg/apis/miskatonic/university_strategy.go
  example/basic/pkg/apis/miskatonic/v1beta1/defaults.go
  example/basic/pkg/apis/olympus/poseidon_strategy.go
  example/kine/pkg/apis/sqlite/tik_strategy.go
  example/podexec/cmd/manager/main.go
  example/podexec/pkg/apis/podexec/pod_strategy.go
  example/podlogs/cmd/manager/main.go
  example/podlogs/pkg/apis/podlogs/pod_strategy.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#415 Chore: Remove generated files from example/podlogs
  example/podlogs/pkg/openapi/openapi_generated.go
  example/podlogs/violations.report
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#416 Bugfix: Replace /swagger.json with /openapi/v2, the former is deprecated
  pkg/cmd/server/start.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#417 Bugfix: Sort structs by names in apiregister-gen
  cmd/apiregister-gen/generators/parser.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#419 add --short-name flag for resource creation commands
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/create/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#420 Bugfix: Upgrade gengo dependency to fix nil panic
  cmd/glide.lock
  cmd/glide.yaml
  cmd/vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  cmd/vendor/k8s.io/gengo/generator/import_tracker.go
  cmd/vendor/k8s.io/gengo/generator/import_tracker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
