Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-11, with the labels that each got.

#438 Bugfix: Admission controller build failure on 1.16
  cmd/apiserver-boot/boot/create/resource.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#436 Fix go vet error 'composite literal uses unkeyed fields' in generated code
  cmd/apiregister-gen/generators/versioned_generator.go
  cmd/apiserver-boot/boot/create/resource.go
  example/basic/Makefile
  test/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#440 Enable admission installation by default on repo-init
  cmd/apiserver-boot/boot/init_repo/repo.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#439 Cut a new release 1.16.alpha.0
  Gopkg.toml
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#443 apiserver-gen: add comment for blank imports
  cmd/apiregister-gen/generators/apis_generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#445 Honor --go-header-file flag in apiregistry-gen
  cmd/apiregister-gen/generators/package.go
  cmd/apiserver-boot/boot/build/generate.go
  cmd/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S
