Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-07, with the labels that each got.

#371 Refact: Deprecate scheme func from versioned pkgs
  cmd/apiregister-gen/generators/apis_generator.go
  cmd/apiregister-gen/generators/install_generator.go
  cmd/apiregister-gen/generators/unversioned_generator.go
  cmd/apiregister-gen/generators/versioned_generator.go
  docs/adding_defaulting.md
  example/pkg/apis/kingsport/v1/festival_types.go
  example/pkg/apis/miskatonic/v1beta1/defaults.go
  example/pkg/apis/miskatonic/v1beta1/university_types.go
  example/pkg/apis/olympus/v1beta1/poseidon_types.go
  example/pkg/apis/olympus/v1beta1/register.go
  pkg/builders/api_group_builder.go
  pkg/builders/api_version_builder.go
  pkg/builders/api_versioned_resource_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#372 Chore: Remove unversion types init scheme func
  cmd/apiregister-gen/generators/unversioned_generator.go
  pkg/builders/api_group_builder.go
  pkg/builders/api_version_builder.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#373 Chore: Move storage to unversioned package to align w/ upstream
  cmd/apiregister-gen/generators/unversioned_generator.go
  cmd/apiregister-gen/generators/versioned_generator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#374 Feat: Adding configurable insecure port to local run command for local debugging
  cmd/apiserver-boot/boot/run/local.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#376 Chore: Compile aa server using gexec.Build
  pkg/test/suite/aggregation.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#375 Feat: Make create resource commands interactive
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/create/util.go
  test/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#377 Release: Bump version to v1.12.alpha.4
  Gopkg.toml
  VERSION
Labels: cncf-cla: yes, size/XS

#381 make OpenAPIConfig works
  pkg/cmd/server/start.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#382 Add support for user defined flags
  cmd/apiserver-boot/boot/init_repo/repo.go
  example/cmd/apiserver/main.go
  pkg/cmd/server/start.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#384 Chore: Fixes broken api-convention link
  docs/concepts/api_building_overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#385 Docs: Scale sub-resource HPA integration
  docs/adding_subresources.md
Labels: approved, cncf-cla: yes, lgtm, size/S
