Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-08, with the labels that each got.

#386 fix invalid resource version in example
  cmd/apiserver-boot/boot/create/create.go
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/create/subresource.go
  cmd/apiserver-boot/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#388 Bugfix: Fixes mutual log verbosity for klog/glog
  pkg/cmd/server/start.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#396 Chore: Remove scheme funcs
  cmd/apiregister-gen/generators/versioned_generator.go
  cmd/apiserver-boot/boot/create/resource.go
  pkg/builders/default_scheme_fns.go
  pkg/builders/resource_interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#406 Release: Cut v1.15.alpha.0 release
  Gopkg.toml
  VERSION
  example/podlogs/Gopkg.lock
  example/podlogs/Gopkg.toml
Labels: approved, cncf-cla: yes, size/XXL

#410 Quit all processes when "apiserver-boot run local" failed
  cmd/apiserver-boot/boot/run/local.go
  cmd/apiserver-boot/boot/run/local_aggregated.go
  cmd/apiserver-boot/boot/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L
