Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-12, with the labels that each got.

#431 go lint error
  pkg/cmd/server/start.go
  pkg/validators/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#446 feat: add envLocalAPIServerBin for avoiding building existed user-customize apiserver
  pkg/test/suite/aggregation.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#447 fix(apiserver-gen): explicit decalre 'k8s.io/apimachinery/pkg/runtime' for apis_generator to avoid goimports bug
  cmd/apiregister-gen/generators/apis_generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#448 fix: remove replace of glog to klog in go.mod
  cmd/go.mod
  cmd/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#450 fix: initializer typo in admission_generator.go
  cmd/apiregister-gen/generators/admission_generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#451 build: upgrade bazel and rules_go version and make bazel work for cmd binaries
  BUILD.bazel
  WORKSPACE
  cmd/apiregister-gen/BUILD.bazel
  cmd/apiregister-gen/generators/BUILD.bazel
  cmd/apiserver-boot/BUILD.bazel
  cmd/apiserver-boot/boot/build/BUILD.bazel
  cmd/apiserver-boot/boot/create/BUILD.bazel
  cmd/apiserver-boot/boot/init_repo/BUILD.bazel
  cmd/apiserver-boot/boot/run/BUILD.bazel
  cmd/apiserver-boot/boot/update/BUILD.bazel
  cmd/apiserver-boot/boot/util/BUILD.bazel
  cmd/apiserver-boot/boot/version/BUILD.bazel
  cmd/apiserver-builder-release/BUILD.bazel
  load.bzl
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#453 feat: use bazel for packaging apiserver-builder
  BUILD.bazel
  cmd/BUILD.bazel
  cmd/apiserver-builder-release/main.go
  cmd/go.mod
  cmd/go.sum
  load.bzl
  pkg/apiserver/BUILD.bazel
  pkg/builders/BUILD.bazel
  pkg/controller/BUILD.bazel
  pkg/test/BUILD.bazel
  pkg/validators/BUILD.bazel
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XL

#455 build: add stamp variables injection for defining apiserver-builder version
  .bazelrc
  cmd/apiserver-boot/boot/version/BUILD.bazel
  cmd/apiserver-boot/boot/version/version.go
  scripts/print-workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#456 Fixes broken step-by-step example link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#457 fix: typo of ServerOutput
  pkg/test/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#458 feat(test): move logic from Start to New for exporting apiserver cmd and options
  cmd/apiserver-boot/boot/create/resource.go
  example/basic/pkg/apis/innsmouth/v1/v1_suite_test.go
  example/basic/pkg/apis/kingsport/v1/v1_suite_test.go
  example/basic/pkg/apis/miskatonic/v1beta1/v1beta1_suite_test.go
  example/basic/pkg/apis/olympus/v1beta1/v1beta1_suite_test.go
  example/kine/pkg/apis/sqlite/v1alpha1/v1alpha1_suite_test.go
  example/podexec/pkg/apis/podexec/v1/v1_suite_test.go
  example/podlogs/pkg/apis/podlogs/v1/v1_suite_test.go
  pkg/test/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#460 Install bazel in travis base
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#459 test: use bazel to get bins while testing
  BUILD.bazel
  cmd/BUILD.bazel
  cmd/apiserver-boot/boot/init_repo/vendor.go
  cmd/apiserver-boot/boot/util/BUILD.bazel
  cmd/apiserver-boot/boot/util/untar.go
  cmd/apiserver-boot/boot/version/BUILD.bazel
  example/basic/BUILD.bazel
  example/basic/build-tools.sh
  test/BUILD.bazel
  test/build-tools.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#461 Using bazel to run "make build"
  Makefile
  scripts/print-workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
