Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-02, with the labels that each got.

#304 Fixes broken travis links in README
  README.md
Labels: cncf-cla: yes, size/XS

#300 fix typo in concepts/aggregation doc
  docs/concepts/aggregation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#305 Chore: Update README title
  README.md
Labels: cncf-cla: yes, size/XS

#309 Feat: Switch logging library to k/klog
  Gopkg.lock
  Gopkg.toml
  cmd/apiregister-gen/generators/controller_generator.go
  cmd/apiregister-gen/main.go
  pkg/builders/api_version_builder.go
  pkg/cmd/server/start.go
  pkg/controller/controller.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
