Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-05, with the labels that each got.

#350 Chore: Refactoring integration testing environment: simpler interfaces
  cmd/apiserver-boot/boot/create/controller_test_suite.go
  example/pkg/controller/festival/festival_controller_suite_test.go
  example/pkg/controller/poseidon/poseidon_controller_suite_test.go
  pkg/test/suite/aggregation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#352 Fix 'controller-manager' binary not found
  cmd/apiserver-boot/boot/build/build_executables.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#354 Bugfix: Run local failure
  cmd/apiserver-boot/boot/create/controller.go
  cmd/apiserver-boot/boot/create/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#355 Chore: Bump version to v1.12.alpha.3
  Gopkg.toml
  OWNERS
  SECURITY_CONTACTS
  VERSION
Labels: cncf-cla: yes, size/S

#357 Feat: Support customizing streaming/long-running endpoints for subresources
  docs/adding_subresources.md
  example/pkg/apis/miskatonic/book_student_rest.go
  example/pkg/apis/miskatonic/pencil_student_rest.go
  example/pkg/apis/miskatonic/v1beta1/book_student_types.go
  example/pkg/apis/miskatonic/v1beta1/pencil_student_types.go
  example/pkg/apis/miskatonic/v1beta1/student_types.go
  pkg/builders/api_group_builder.go
  pkg/builders/scheme.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#359 Chore: Custom REST extending shortname/catagory example
  example/pkg/apis/miskatonic/student_rest.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
