Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-10, with the labels that each got.

#425 Cut v1.15.alpha.1 release
  Gopkg.toml
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#421 Chore: Go mod support for apiserver-boot
  cmd/go.mod
  cmd/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#427 delete duplicated line in package build
  cmd/apiserver-boot/boot/build/docs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#429 Fixed doc adding_non_namespaced_resources with correct steps
  docs/adding_non_namespaced_resources.md
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash
