Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2019-03, with the labels that each got.

#310 Chore: Revise subresource docs: avoid scale as example
  docs/adding_subresources.md
Labels: cncf-cla: yes, size/M

#318 Chore: Revise apiserver-boot resource group flag explanation
  cmd/apiserver-boot/boot/create/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#319 Chore: Update apiserver-boot version's compile-in default kubernetes vendor version
  cmd/apiserver-builder-release/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 QueueWorker can work with infinite retry
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#321 Bugfix: Support alias on primitive types
  cmd/apiregister-gen/generators/parser.go
  cmd/apiregister-gen/generators/unversioned_generator.go
  example/.gitignore
  example/pkg/apis/innsmouth/v1/deepone_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#322 Bugfix: Ensure GOROOT env var on running openapi-gen
  cmd/apiserver-boot/boot/build/generate.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#315 Feat: Support customizing REST for subresource
  cmd/apiregister-gen/generators/parser.go
  cmd/apiregister-gen/generators/unversioned_generator.go
  cmd/apiregister-gen/generators/versioned_generator.go
  cmd/apiserver-boot/boot/create/subresource.go
  example/pkg/apis/miskatonic/v1beta1/computer_student_types.go
  example/pkg/apis/miskatonic/v1beta1/computer_student_types_test.go
  example/pkg/apis/miskatonic/v1beta1/student_types.go
  example/pkg/apis/miskatonic/v1beta1/university_types.go
Labels: cncf-cla: yes, size/L

#325 Bugfix: sync dep toml version for apiserver-builder-alpha
  Gopkg.toml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#326 Feat: Plumb generic options to new custom rest constructor
  cmd/apiregister-gen/generators/versioned_generator.go
  example/pkg/apis/miskatonic/student.go
  example/pkg/apis/miskatonic/student_computer.go
  example/pkg/apis/miskatonic/v1beta1/computer_student_types.go
  example/pkg/apis/miskatonic/v1beta1/student_types.go
  pkg/builders/api_versioned_resource_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#327 Chore: Move all generated strategy to unversioned package
  cmd/apiregister-gen/generators/versioned_generator.go
  cmd/apiserver-boot/boot/create/resource.go
  example/pkg/apis/kingsport/festival_strategy.go
  example/pkg/apis/kingsport/v1/festival_types.go
  example/pkg/apis/miskatonic/student_computer_rest.go
  example/pkg/apis/miskatonic/student_rest.go
  example/pkg/apis/miskatonic/university_strategy.go
  example/pkg/apis/miskatonic/v1beta1/university_types.go
  example/pkg/apis/olympus/poseidon_strategy.go
  example/pkg/apis/olympus/v1beta1/poseidon_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/squash

#328 Feat: Migrate subresource rest to unversioned package
  cmd/apiregister-gen/generators/versioned_generator.go
  cmd/apiserver-boot/boot/create/subresource.go
  example/pkg/apis/miskatonic/campus_university_rest.go
  example/pkg/apis/miskatonic/v1beta1/campus_university_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#329 Chore: Update docs for subresource and custom REST
  docs/adding_custom_rest.md
  docs/adding_subresources.md
Labels: approved, cncf-cla: yes, lgtm, size/S
