Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2020-09, with the labels that each got.

#532 Chore: Warning messages when running code-gen under go mod projects
  cmd/apiserver-boot/boot/build/generate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#533 Adding example project that using hostpath as storage
  example/non-etcd/.gitignore
  example/non-etcd/BUILD.bazel
  example/non-etcd/PROJECT
  example/non-etcd/WORKSPACE
  example/non-etcd/boilerplate.go.txt
  example/non-etcd/cmd/apiserver/main.go
  example/non-etcd/cmd/manager/main.go
  example/non-etcd/docs/examples/burger/burger.yaml
  example/non-etcd/go.mod
  example/non-etcd/go.sum
  example/non-etcd/pkg/apis/doc.go
  example/non-etcd/pkg/apis/filepath/burger_rest.go
  example/non-etcd/pkg/apis/filepath/burger_strategy.go
  example/non-etcd/pkg/apis/filepath/doc.go
  example/non-etcd/pkg/apis/filepath/install/doc.go
  example/non-etcd/pkg/apis/filepath/v1/burger_types.go
  example/non-etcd/pkg/apis/filepath/v1/burger_types_test.go
  example/non-etcd/pkg/apis/filepath/v1/doc.go
  example/non-etcd/pkg/apis/filepath/v1/v1_suite_test.go
  example/non-etcd/pkg/controller/add_burger.go
  example/non-etcd/pkg/controller/burger/burger_controller.go
  example/non-etcd/pkg/controller/burger/burger_controller_suite_test.go
  example/non-etcd/pkg/controller/burger/burger_controller_test.go
  example/non-etcd/pkg/controller/controller.go
  example/non-etcd/pkg/controller/doc.go
  example/non-etcd/pkg/doc.go
  example/non-etcd/pkg/openapi/doc.go
  example/non-etcd/pkg/webhook/webhook.go
  example/non-etcd/plugin/admission/burger/admission.go
  example/non-etcd/plugin/admission/initializer.go
  example/non-etcd/sample/burger.yaml
  go.mod
  pkg/storage/filepath/jsonfile_rest.go
  pkg/storage/filepath/jsonfile_rest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#539 updates documentation for required flags
  docs/concepts/api_building_overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#540 Chore: Bump k8s dependency to 1.19
  .gitignore
  example/basic/pkg/apis/miskatonic/student_rest.go
  example/kine/pkg/apis/mysql/tiger_rest.go
  go.mod
  go.sum
  pkg/builders/api_versioned_resource_builder.go
  pkg/cmd/server/start.go
Labels: approved, cncf-cla: yes, lgtm, size/L
