Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2020-03, with the labels that each got.

#484 Overridable CGO options for `build executables' commands
  cmd/apiserver-boot/boot/build/build_executables.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#485 Initialize a dep compatible go mod configuration
  cmd/apiregister-gen/generators/admission_generator.go
  cmd/apiserver-boot/boot/create/controller.go
  cmd/apiserver-boot/boot/create/controller_test_suite.go
  cmd/go.sum
  example/basic/go.mod
  example/basic/go.sum
  example/kine/go.mod
  example/podexec/go.mod
  example/podlogs/go.mod
  go.mod
  go.sum
  test/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#487 Bump v1.16.alpha.2
  Gopkg.toml
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Fix apiVersions of Deployment and StatefulSet resources
  cmd/apiserver-boot/boot/build/build_resource_config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#490 Support go mod for generated new vendorless projects
  .gitignore
  BUILD.bazel
  Makefile
  cmd/BUILD.bazel
  cmd/apiserver-boot/boot/init_repo/repo.go
  cmd/apiserver-boot/boot/util/untar.go
  example/basic/Makefile
  go.mod.new
Labels: approved, cncf-cla: yes, lgtm, size/L

#491 Refactor go:generated from GOBIN
  cmd/apiserver-boot/boot/create/group.go
  cmd/apiserver-boot/boot/create/version.go
  cmd/apiserver-boot/boot/init_repo/repo.go
  example/basic/go.sum
  example/basic/pkg/apis/doc.go
  example/basic/pkg/apis/innsmouth/doc.go
  example/basic/pkg/apis/innsmouth/v1/doc.go
  example/basic/pkg/apis/kingsport/doc.go
  example/basic/pkg/apis/kingsport/v1/doc.go
  example/basic/pkg/apis/miskatonic/doc.go
  example/basic/pkg/apis/miskatonic/v1beta1/doc.go
  example/basic/pkg/apis/olympus/doc.go
  example/basic/pkg/apis/olympus/v1beta1/doc.go
  example/basic/pkg/openapi/doc.go
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L
