Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2020-10, with the labels that each got.

#542 Rebasing latest kubebuilder controller scafolding to land onto controller-runtime
  .github/workflows/build.yml
  BUILD.bazel
  cmd/apiserver-boot/boot/create/BUILD.bazel
  cmd/apiserver-boot/boot/create/controller.go
  cmd/apiserver-boot/boot/create/controller_test_suite.go
  cmd/apiserver-boot/boot/create/controllertest.go
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/init_repo/BUILD.bazel
  cmd/apiserver-boot/boot/init_repo/repo.go
  cmd/apiserver-boot/boot/util/util.go
  go.mod
  go.mod.new
  go.sum
  repos.bzl
  test/Makefile.test
  test/tweak-go-mod.sh
  vendor.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#545 Chore: Remove references to incubator
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#552 Rebasing apiserver-runtime pt2
  .github/workflows/build.yml
  Makefile
  Makefile.test
  VERSION
  cmd/apiserver-boot/BUILD.bazel
  cmd/apiserver-boot/boot/build/build_container.go
  cmd/apiserver-boot/boot/build/build_executables.go
  cmd/apiserver-boot/boot/create/group.go
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/create/subresource.go
  cmd/apiserver-boot/boot/create/util.go
  cmd/apiserver-boot/boot/create/version.go
  cmd/apiserver-boot/boot/init_repo/repo.go
  cmd/apiserver-boot/boot/run/in_cluster.go
  cmd/apiserver-boot/boot/run/local.go
  cmd/apiserver-boot/boot/run/local_aggregated.go
  cmd/apiserver-boot/boot/util/BUILD.bazel
  cmd/apiserver-boot/boot/util/repo.go
  cmd/apiserver-boot/boot/util/util.go
  cmd/apiserver-boot/main.go
  go.mod
  scripts/install_etcd.sh
  scripts/print-workspace-status.sh
  scripts/workspace-install.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#553 Status subresource refactoring
  .github/workflows/build.yml
  cmd/apiserver-boot/boot/create/create.go
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/init_repo/repo.go
  cmd/apiserver-boot/boot/util/util.go
  example/basic/controllers/storage/suite_test.go
  example/basic/controllers/storage/volumeclaim_controller.go
  example/basic/go.mod
  example/basic/go.sum
  example/basic/pkg/apis/innsmouth/v1/deepone_types.go
  example/basic/pkg/apis/kingsport/v1/festival_types.go
  example/basic/pkg/apis/miskatonic/v1beta1/campus_university_types.go
  example/basic/pkg/apis/miskatonic/v1beta1/computer_student_types.go
  example/basic/pkg/apis/miskatonic/v1beta1/student_types.go
  example/basic/pkg/apis/miskatonic/v1beta1/university_types.go
  example/basic/pkg/apis/olympus/v1beta1/poseidon_types.go
  scripts/workspace-install.sh
  test/BUILD.bazel
  test/boilerplate.go.txt
  test/build-tools.sh
  test/install-kubebuilder.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#554 Chore: Minor changes on examples and build config subcommands
  .github/workflows/build.yml
  cmd/apiserver-boot/boot/build/build_resource_config.go
  cmd/apiserver-boot/boot/create/resource.go
  cmd/apiserver-boot/boot/init_repo/repo.go
  example/basic/build-tools.sh
  example/basic/install-kubebuilder.sh
  example/basic/pkg/apis/innsmouth/v1/deepone_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#555 Split build config yamls
  cmd/apiserver-boot/boot/build/build_resource_config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#556 Re-gen certificates for basic example
  .github/workflows/build.yml
  cmd/apiserver-boot/boot/build/build_resource_config.go
  example/basic/config/aggregated-apiserver.yaml
  example/basic/config/apiserver.yaml
  example/basic/config/apiservice.yaml
  example/basic/config/certificates/apiserver.crt
  example/basic/config/certificates/apiserver.key
  example/basic/config/certificates/apiserver_ca.crt
  example/basic/config/certificates/apiserver_ca.key
  example/basic/config/controller-manager.yaml
  example/basic/config/etcd.yaml
  example/basic/config/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#558 Basic watcher
  example/non-etcd/go.mod
  example/non-etcd/go.sum
  pkg/storage/filepath/jsonfile_rest.go
  pkg/storage/filepath/jsonfile_rest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#550 implement rest.Scoper, return filesystem errors fixes #549
  example/non-etcd/go.mod
  example/non-etcd/go.sum
  pkg/storage/filepath/jsonfile_rest.go
  pkg/storage/filepath/jsonfile_rest_test.go
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, size/XL
