Repository kubernetes-sigs/apiserver-builder-alpha, pull requests merged in 2020-08, with the labels that each got.

#516 update documnet
  docs/building_docs.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#503 sheet
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#499 broken link for api conversion
  docs/compare_with_kubebuilder.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#495 Remove redundant blobs / masters from links
  docs/adding_custom_rest.md
  docs/tools_user_guide.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#494 fix broken link : https://git.k8s.io/community/contributors/guide/con…
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#523 Test env windows support
  pkg/test/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#522 Get vendor tarball back for faster code-generation
  .gitignore
  BUILD.bazel
  Makefile
  cmd/apiserver-boot/boot/build/build_container.go
  cmd/apiserver-boot/boot/create/BUILD.bazel
  cmd/apiserver-boot/boot/init_repo/repo.go
  cmd/apiserver-boot/boot/util/untar.go
  example/basic/Makefile
  example/basic/cmd/manager/main.go
  example/basic/go.mod
  example/basic/go.sum
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/builders/shortcut_storage_wrapper.go
  pkg/cmd/server/start.go
  pkg/controller/controller.go
  repos.bzl
  test/Makefile
  vendor.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#525 Adding github actions configurations
  .github/workflows/build.yml
Labels: approved, cncf-cla: yes, size/M

#526 Chore: Github actions follow-up pt2
  .github/workflows/build.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#527 Github action pt3: prunes travis configurations
  .github/workflows/build.yml
  README.md
  scripts/workspace-install.sh
  test/travis.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#528 Chore: Santize go mod
  example/basic/go.mod
  go.mod.new
Labels: approved, cncf-cla: yes, lgtm, size/M

#529 Chore: Container build test job
  .github/workflows/build.yml
  example/basic/config/apiserver.yaml
  example/basic/config/certificates/apiserver.crt
  example/basic/config/certificates/apiserver.csr
  example/basic/config/certificates/apiserver.key
  example/basic/config/certificates/apiserver_ca.crt
  example/basic/config/certificates/apiserver_ca.key
  example/basic/config/certificates/apiserver_ca.srl
  example/basic/config/rbac.yaml
  example/basic/go.mod
  example/basic/go.sum
  example/basic/pkg/controller/festival/festival_controller.go
  example/basic/sample/festival.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#530 Enable all admission plugins and grants rbac permission
  .github/workflows/build.yml
  cmd/apiserver-boot/boot/build/build_resource_config.go
  example/basic/config/apiserver.yaml
  example/basic/config/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
